STM/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join/', join, name='join'),
    path('join_success/', join_success, name='join_success'),
    path('drop/', drop, name='drop'),
    path('drop_success', drop_success, name='drop_success'),
]

code_review/py/data_save/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import profileRegister, profileEdit, memberlist

app_name = "data_save"


urlpatterns = [
    path('', profileRegister, name='profileRegister'),
    path('edit/<int:pk>/', profileEdit, name='profileEdit'),
    path('memberlist/', memberlist, name='memberlist'),
]

data_save/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import profileRegister, profileEdit, memberlist

app_name = "data_save"


urlpatterns = [
    path('', profileRegister, name='profileRegister'),
    path('edit/', profileEdit, name='profileEdit'),
    path('memberlist/', memberlist, name='memberlist'),
]

reservation_project/urls.py
# -*- coding: utf-8 -*-
"""ReservationProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# app 고도화 작업 v1.0 DCR in AWS ECR

"""
dhdiagram.net/admin : 점포 관리자 서비스
dhdiagram.net/reservation : 예악서비스
dhdiagram.net/auth : 일반유저 회원가입 서비스
dhdiagram.net/data_save : 예액내역 저장 서비스
dhdiagram.net/ : api 서비스
dhdiagram.net/push : 문자발송 서비스
dhdiagram.net/stm : 최고 관리자(점포관리자) 회원가입
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')), 
    path('auth/', include('authentication.urls')), 
    path('data_save/', include('data_save.urls')), 
    path('', include('reservation_api.urls')), 
    path('push/', include('pushEngine.urls')), 
    path('businessRegister/', include('BusinessRegister.urls')),
    path('cafe_manager/', include('cafe_manager.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#administrator site page title
admin.site.site_header = '통합예약/적립시스템'

data_save/models.py
from django.db import models

class profile(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=20)
    address_01 = models.CharField(max_length=200)
    address_02 = models.CharField(max_length=200)
    #password = models.CharField(max_length=10)
    #created_date = models.DateTimeField(auto_now_add=True)
    #published_date = models.DateTimeField(null=True, blank=True)

data_save/forms.py
from django import forms
from .models import profile

class profileForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['name','email','phone','address_01','address_02']

    name = forms.CharField(label='이름')
    email = forms.EmailField(label='이메일')
    phone = forms.CharField(label='핸드폰')
    address_01 = forms.CharField(label='주소')
    address_02 = forms.CharField(label='상세주소')

code_review/py/data_save/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import profileForm
from .models import profile
from django.http import HttpResponse



def profileEdit(request, pk):
    s_data = get_object_or_404(profile, pk=pk)
    if request.method == 'POST':
        form = profileForm(request.POST, instance=s_data)
        if form.is_valid():
            form.save()
            return HttpResponse('정보수정이 완료되었습니다')
        print(form.errors)
        return HttpResponse('에러가 발생하였습니다')
    else:
        form = profileForm(instance=s_data)
        context = {
            'form':form,
            'obj': s_data,
            'writing':True,
            'now':'profileEdit',
        }
        #return render(request, 'data_save/profile_edit.html', {'form':form})
        return render(request, 'data_save/profile_edit.html', context)



def profileRegister(request):
    if request.method == 'GET':
        form = profileForm(request.GET)
        return render(request, 'data_save/profile.html' , {'form':form})
    elif request.method == 'POST':
        form = profileForm(request.POST)
        if form.is_valid():
            post = form.save()
            name = request.POST["name"]
            email = request.POST["email"]
            phone = request.POST["phone"]
            address_01 = request.POST["address_01"]
            address_02 = request.POST["address_02"]
            print(request.POST["name"])
            print(request.POST["email"])
            print(request.POST["phone"])
            print(request.POST["address_01"])
            print(request.POST["address_02"])
            return redirect ('data_save:memberlist')
        else:
            print(form.errors)
            return HttpResponse('에러가 발생하였습니다')


def memberlist(request):
    members = profile.objects.order_by('-id')[:1]
    return render(request, 'data_save/member_all.html' , {'members': members})

data_save/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import profileForm
from .models import profile
from django.http import HttpResponse



def profileEdit(request):
    if request.method == 'POST':
        s_data = profile.objects.get(id=request.POST['member_choice'])
        form = profileForm(request.POST, instance=s_data)
        if form.is_valid():
            s_data.name = form.cleaned_data['name']
            s_data.email = form.cleaned_data['email']
            s_data.phone = form.cleaned_data['phone']
            s_data.address_01 = form.cleaned_data['address_01']
            s_data.address_02 = form.cleaned_data['address_02']
            s_data.save()
            return HttpResponse('정보수정이 완료되었습니다')
            print(form.errors)
            return HttpResponse('에러가 발생하였습니다')
    else:
        form = profileForm(instance=s_data)
        context = {
            'form':form,
            'writing':True,
            'now':'profileEdit',
        }
        #return render(request, 'data_save/profile_edit.html', {'form':form})
        return render(request, 'data_save/profile_edit.html', context)


# 회원가입
def profileRegister(request):
    if request.method == 'GET':
         form = profileForm(request.GET)
         return render(request, 'data_save/profile.html' , {'form':form})
    elif request.method == 'POST':
        form = profileForm(request.POST)
        if form.is_valid():
            post = form.save()
            members = get_object_or_404(profile, id=int(request.GET.get('mem_register',0)))
            new_register = profile(
                name = members.name,
                email = members.email,
                phone = members.phone,
                address_01 = members.address_01,
                address_02 = members.address_02,
            )
            new_register.save()
            return redirect('data_save:memberlist')


def memberlist(request):
    members = profile.objects.order_by('-id')[:1]
    return render(request, 'data_save/member_all.html' , {'members': members})

data_save/templates/data_save/profile.html
{% block content %}
<form method="POST" action="{% url 'data_save:profileRegister' %}">
{% csrf_token %}
<!--<input type="hidden" name="mem_register" value="{{ member.id }}" />-->
<head>

<style>
li {
    list-style:none;
}
</style>
</head>
</head>
<div>
<p style=font-size:13px;>
<br/>
<br/>
<div style="width:100%; text-align:center; font-size:12px; margin-left:10px;">
<strong style="text-decoration:underline;">회원가입 페이지 입니다. 아래의 정보를 모두 빠짐없이 정확하게 입력하여 주세요</strong>
</div>
</p>
<div class="infobox" style="width:100%; text-align:center">
<ul>
<li>{{ form.username }}</li>
<li style="margin-top:10px;">이름 | {{ form.name }}</li>  
<li style="margin-top:10px;">이메일 | {{ form.email }}</li>
<li style="margin-top:10px;">휴대폰 | {{ form.phone }}</li>
<li style="margin-top:10px;">주소1 | {{ form.address_01 }}</li>
<li style="margin-top:10px;">주소2 | {{ form.address_02 }}</li>
</ul>
</div>
<div style="width:100%; text-align:center; margin-left:20px;">
<button type="submit">가입하기</button>
</form>
</div>
{% endblock %}
<br/>
<br/>
<div>
<br/>
<br/>
</div>

data_save/templates/data_save/profile_edit.html
{% block content %}
<form method="POST" enctype="multipart/form-data" action="{% url 'data_save:memberlist' %}">{% csrf_token %}
<head>

<style>
li {
    list-style:none;
}
</style>
</head>
</head>
<div>
<p style=font-size:13px;>
<br/>
<br/>
<div style="width:100%; text-align:center; font-size:12px; margin-left:10px;">
<strong style="text-decoration:underline;">회원정보 수정 페이지 입니다. 정보를 수정해 주세요</strong>
</div>
</p>
<div class="infobox" style="width:100%; text-align:center">
<ul>
<li>{{ form.username }}</li>
<li style="margin-top:10px;">이름 | {{ form.name }}</li>  
<li style="margin-top:10px;">이메일 | {{ form.email }}</li>
<li style="margin-top:10px;">휴대폰 | {{ form.phone }}</li>
<li style="margin-top:10px;">주소1 | {{ form.address_01 }}</li>
<li style="margin-top:10px;">주소2 | {{ form.address_02 }}</li>
</ul>
</div>
<div style="width:100%; text-align:center; margin-left:20px;">
<input type="hidden" name="member_choice" value="{{ member.id }}">수정하기

</form>
</div>
{% endblock %}
<br/>
<br/>
<div>
<br/>
<br/>
</div>