STM/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join/', join, name='join'),
    path('join_success/', join_success, name='join_success'),
    path('drop/', drop, name='drop'),
    path('drop_success', drop_success, name='drop_success'),
]

reservation/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import email_ticket, ticket_list, my_tc_list, revstart, eticket_resend, index, course_search, payment, date_search_result, date_search, intro, payment

app_name = "reservation"


urlpatterns = [
    path('', index, name='index'),
    path('revstart/', revstart, name='revstart'),  # 예약시작 페이지
    path('intro/', intro, name='intro'),  # 회원가입 or 예매페이지이동
    # path('revstart/schedule', schedule, name='schedule'),
    # path('revsuccess/', revsuccess, name='revsuccess'),
    path('course_search/', course_search, name='course_search'),  # 조건에 따른 향공티켓 일정표 출력 페이지
    path('payment/', payment, name='payment'),  # 결제 및 항공권 티켓 발송 페이지
    path('date_search/', date_search, name='date_search'),  # 날짜별 항공권 조회 페이지
    path('date_search_result/', date_search_result, name='date_search_result'),  # 날짜별 조회에 따른 결과 출력 페이지
    path('eticket_resend/', eticket_resend, name='eticket_resend'), #티켓 제전송 기능
    path('email_ticket/', email_ticket, name='email_ticket'), #이메일로 티켓 발송
    path('ticket_list/', ticket_list, name='ticket_list'), #나의 예약 리스트
    path('my_tc_list/', my_tc_list, name='my_tc_list') 
]

reservation_project/urls.py
# -*- coding: utf-8 -*-
"""ReservationProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# app 고도화 작업 v1.0 DCR in AWS ECR

"""
dhdiagram.net/admin : 점포 관리자 서비스
dhdiagram.net/reservation : 예악서비스
dhdiagram.net/auth : 일반유저 회원가입 서비스
dhdiagram.net/data_save : 예액내역 저장 서비스
dhdiagram.net/ : api 서비스
dhdiagram.net/push : 문자발송 서비스
dhdiagram.net/stm : 최고 관리자(점포관리자) 회원가입
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')), 
    path('auth/', include('authentication.urls')), 
    path('data_save/', include('data_save.urls')), 
    path('', include('reservation_api.urls')), 
    path('push/', include('pushEngine.urls')), 
    path('businessRegister/', include('BusinessRegister.urls')),
    path('cafe_manager/', include('cafe_manager.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#administrator site page title
admin.site.site_header = '통합예약/적립시스템'

code_review/py/reservation/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from .forms import reservationForm, datesearchForm, emailTicketForm
from .models import flightSection, seatClass, emailTicket
from django.http import HttpResponse, Http404, HttpResponseNotFound
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.utils import timezone
from django.conf import settings

def index(request):
    return render(request, 'reservation/index.html')


def intro(request):
    return render(request, 'reservation/intro.html')


# 예약 완료 후 티켓발송
def eticket_send(request):
    courses = flightSection.objects.get(id=request.POST['course_choice'])
    title = "[KAL-E-TICKET]예약이 완료되었습니다(E-TICKET발송안내)"
    html_messsage = render_to_string('reservation/eticket.html', {'courses': courses})
    email = EmailMessage(title, html_messsage, to=['dhdiagram@gmail.com'])
    email.content_subtype = "html"
    return email.send()


# 예약 완료 후 티켓수동발송
def eticket_resend(request):
    courses = flightSection.objects.get(id=request.POST['course_choice'])
    title = "[KAL-E-TICKET]항공권 발송완료(E-TICKET발송)"
    html_messsage = render_to_string('reservation/eticket.html', {'courses': courses})
    email = EmailMessage(title, html_messsage, to=[request.POST["email"]])
    email.content_subtype = "html"
    return email.send(courses)


#예약 기록 저장 --> email_ticket
def email_ticket(request):
    if request.method == 'POST':
        courses = get_object_or_404(flightSection, id=int(request.GET.get('course_choice', 0)))
        form = emailTicketForm(request.POST)
        if form.is_valid():
            post = form.save()
            # starting_point = request.POST["starting_point"]
            # arrival = request.POST["arrival"]
            # flight_time = request.POST["flight_time"]
            # daytogo = request.POST["daytogo"]
            # comingDay = request.POST["comingDay"]  
            return redirect('reservation:revstart')
        return render(request, 'reservation/payment.html', {'courses': courses, 'form': form})
    else:
        courses = get_object_or_404(flightSection, id=int(request.GET.get('course_choice', 0)))
        new_ticket = emailTicket(
            starting_point=courses.starting_point,
            arrival=courses.arrival,
            flight_time=courses.flight_time,
            daytogo=courses.daytogo,
            comingDay=courses.comingDay,
            user=request.user
        )
        new_ticket.save()
        # form = emailTicketForm()
        return render(request, 'reservation/payment.html', {'courses': courses})
        # return redirect('reservation:revstart')

# @login_required
def date_search(request):
    if request.method == 'POST':
        form = datesearchForm(request.POST)
        if form.is_valid():
            return render(request, 'reservation/course_list.html', {'courses': courses}) 
    else:
        form = datesearchForm()
    return render(request, 'reservation/date_search.html', {'form': form})


#@login_required
def revstart(request):
    print(request.user)
    if request.method == 'POST':
        form = reservationForm(request.POST)
        if form.is_valid():
            post = form.save()
            starting_point = request.POST["starting_point"]
            arrival = request.POST["arrival"]
            flight_time = request.POST["flight_time"]
            daytogo = request.POST["daytogo"]
            comingDay = request.POST["comingDay"]
            SeatClass = request.POST["SeatClass"]
        return redirect('reservation:course_search')
    else:
        form = reservationForm()
    return render(request, 'reservation/rev_start.html', {'form': form})



def payment(request):
    if request.method == 'POST':
        courses = flightSection.objects.get(id=request.POST['course_choice'])
        form = emailTicketForm(request.POST)
        if form.is_valid():
            post = form.save()
            starting_point = request.POST["starting_point"]
            arrival = request.POST["arrival"]
            flight_time = request.POST["flight_time"]
            daytogo = request.POST["daytogo"]
            comingDay = request.POST["comingDay"]
            eticket_send(request)
        return render(request, 'reservation/payment.html', {'courses': courses})


        
# 티켓조회 및 해당 일자에 티켓이 없을 시 별도 안내 페이지 요청
# @login_required
def course_search(request):
    courses = flightSection.objects.filter(
        starting_point=request.GET.get('starting_point', ''),
        arrival=request.GET.get('arrival', ''),
        daytogo=request.GET.get('daytogo', ''),
        comingDay=request.GET.get('comingDay', ''),
        SeatClass=request.GET.get('SeatClass', '')
    )
    if courses.exists():
        return render(request, 'reservation/course_list.html', {'courses': courses})
    else:
        return render(request, 'reservation/sch_does_not_exist.html')


# 날짜기반 항공권 조회기능
def date_search_result(request):
    try:
        courses = flightSection.objects.filter(daytogo=request.GET['daytogo'])
    except courses.DoesNotExist:
        raise Http404("해당 출발일에 항공 여정이 없습니다")
    return render(request, 'reservation/date_list.html', {
        'courses': courses,
    })

reservation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import reservationForm, datesearchForm, emailTicketForm
from .models import flightSection, seatClass, emailTicket
from django.http import HttpResponse, Http404, HttpResponseNotFound
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.utils import timezone

import os
from twilio.rest import Client


def index(request):
    return render(request, 'reservation/index.html')


def intro(request):
    return render(request, 'reservation/intro.html')

    
# 예약 완료 후 티켓발송 및 티켓 내용 SMS 전달
def eticket_send(request):
    courses = flightSection.objects.get(id=request.POST['course_choice'])
    title = "[TICKET]예약이 완료되었습니다"
    html_messsage = render_to_string('reservation/eticket.html', {'courses': courses})
    email = EmailMessage(title, html_messsage, to=['dhdiagram@gmail.com'])
    email.content_subtype = "html"
    return email.send()

    account_sid = os.environ['TWILIO_ACCOUNT_SID']
    auth_token = os.environ['TWILIO_AUTH_TOKEN']
    client = Client(account_sid, auth_token)

    message = client.messages.create(
                                  #body='AWS codepipeline deploy success!!!', - plain text
                                  body= html_messsage,
                                  from_='+16468460142',
                                  to='+8201021764011'
                                )



# 예약 완료 후 티켓수동발송 및 SMS 재발송
def eticket_resend(request):
    courses = flightSection.objects.get(id=request.POST['course_choice'])
    title = "[KAL-E-TICKET]항공권 발송완료(E-TICKET발송)"
    html_messsage = render_to_string('reservation/eticket.html', {'courses': courses})
    email = EmailMessage(title, html_messsage, to=[request.POST["email"]])
    email.content_subtype = "html"
    return email.send(courses)
    account_sid = os.environ['TWILIO_ACCOUNT_SID']
    auth_token = os.environ['TWILIO_AUTH_TOKEN']
    client = Client(account_sid, auth_token)

    message = client.messages.create(
                                  #body='AWS codepipeline deploy success!!!', - plain text
                                  body= html_messsage,
                                  from_='+16468460142',
                                  to='+8201021764011'
                                )


#예약 기록 저장 --> email_ticket
def email_ticket(request):
    if request.method == 'POST':
        courses = get_object_or_404(flightSection, id=int(request.GET.get('course_choice',0)))
        form = emailTicketForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('reservation:revstart')
        return render(request, 'reservation/payment.html', {'courses':courses, 'form':form})
    else:
        courses = get_object_or_404(flightSection, id=int(request.GET.get('course_choice',0)))
        new_ticket = emailTicket(
            starting_point = courses.starting_point,
            arrival = courses.arrival,
            flight_time = courses.flight_time,
            daytogo = courses.daytogo,
            comingDay = courses.comingDay,
            Price = courses.Price,
            SeatClass = courses.SeatClass,
            user = request.user
        )
        new_ticket.save()
        return render(request, 'reservation/payment.html' , {'courses':courses})


# @login_required
def date_search(request):
    if request.method == 'POST':
        form = datesearchForm(request.POST)
        if form.is_valid():
            return render(request, 'reservation/course_list.html', {'courses': courses}) 
    else:
        form = datesearchForm()
    return render(request, 'reservation/date_search.html', {'form': form})


#@login_required
def revstart(request):
    if request.method == 'POST':
        form = reservationForm(request.POST)
        if form.is_valid():
            post = form.save()
            starting_point = request.POST["starting_point"]
            arrival = request.POST["arrival"]
            flight_time = request.POST["flight_time"]
            daytogo = request.POST["daytogo"]
            comingDay = request.POST["comingDay"]
            SeatClass = request.POST["SeatClass"]
        return redirect('reservation:course_search')
    else:
        form = reservationForm()
    return render(request, 'reservation/rev_start.html', {'form': form})


# 예약내역 리스트
#@login_required method
def login_check(func):
    def wrapper(request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user is None:
            return render(request, 'authentication/idpw_does_not_exist.html')
    return wrapper

#@login_check
# 전체 예약내역 리스트
def ticket_list(request):
    if request.method == 'GET':
        tc_lists = emailTicket.objects.all()
        return render(request, 'reservation/ticket_list.html', {'tc_lists': tc_lists})
    else:
        form = emailTicketForm()
    return render(request, 'reservation/rev_start.html', {'form':form})


# 나의 예약 내역 리스트
def my_tc_list(request):
    if request.method == 'GET':
        my_tickets = emailTicket.objects.filter(id=request.GET.get('myticket'))
        return render(request, 'reservation/my_ticket_list.html', {'my_tickets':my_tickets})
    else:
        form = emailTicketForm()
    return render(request, 'reservation/rev_start.html', {'form':form})


# 예약 후 예약 결과를 Email Ticket 테이블에 저장
def payment(request):
    if request.method == 'POST':
        courses = flightSection.objects.get(id=request.POST['course_choice'])
        form = emailTicketForm(request.POST)
        if form.is_valid():
            post = form.save()
            starting_point = request.POST["starting_point"]
            arrival = request.POST["arrival"]
            flight_time = request.POST["flight_time"]
            daytogo = request.POST["daytogo"]
            comingDay = request.POST["comingDay"]
            Price = request.POST["Price"]
            SeatClass = request.POST["SeatClass"]
            eticket_send(request)
        return render(request, 'reservation/payment.html', {'courses': courses})


        
# 티켓조회 및 해당 일자에 티켓이 없을 시 별도 안내 페이지 요청
# @login_required
def course_search(request):
    courses = flightSection.objects.filter(
        starting_point = request.GET.get('starting_point',''), #없으면 None 반환
        arrival = request.GET.get('arrival',''),
        daytogo = request.GET.get('daytogo',''),
        comingDay = request.GET.get('comingDay',''),
        SeatClass = request.GET.get('SeatClass','')
    )
    if courses.exists(): # 검색한 코스가 DB에 존재하면
        return render(request, 'reservation/course_list.html', {'courses':courses})
    else:
        return render(request, 'reservation/sch_does_not_exist.html')


# 날짜기반 항공권 조회기능 (qs search)
def date_search_result(request):
    try:
        courses = flightSection.objects.filter(daytogo=request.GET['daytogo'])
    except courses.DoesNotExist:
        raise Http404("해당 출발일에 항공 여정이 없습니다")
    return render(request, 'reservation/date_list.html', {
        'courses': courses,
    })

reservation/templates/reservation/course_list.html
{% block content %}
{% load static %}
<img src="{% static "/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/csbground.jpg" %}">
{% for course in courses %}
<form action="{% url 'reservation:email_ticket' %}" method="GET">
{% csrf_token %}
<input type="hidden" name="course_choice" value="{{ course.id }}" />

<br/>
<style>
*/
ul{
    list-style:none;
}
</style>
<div id="wrapper" style="margin-bottom:30px;">
<ul style="border:1px; color:black;">
<li style="float:left"><strong>ID| {{ course.id }}</strong><br/></li>
<li style="float:left; margin-left:30px;"><strong>기종| {{ course.FlightNumber }}</strong><br/></li>
<li style="float:left; margin-left:30px;"><strong>편명| {{ course.FlightAircraft }}</strong><br/></li>
<li style="float:left; margin-left:30px;"><strong>출발| {{ course.starting_point }}</strong><br/></li>
<li style="float:left; margin-left:30px;"><strong>도착 | {{ course.arrival }}</strong><br/></li>
<li style="float:left; margin-left:30px;">가는날 | {{ course.daytogo | date:'Y/m/d' }}<br/></li>
<li style="float:left; margin-left:30px;">오는날 | {{ course.comingDay | date:'Y/m/d' }} <br/></li>
<li style="float:left; margin-left:30px;">비행시간 | {{ course.flight_time | date:'H:i' }}<br/></li>
<li style="float:left; margin-left:30px;">좌석 | {{ course.SeatClass }}<br/></li>
<li style="float:left; margin-left:30px;">가격 | {{ course.Price }}<br/></li>
<li style="float:left; margin-left:1100px; position:absolute;"><button type="submit">예약하기</button></li>
</ul>
</form>
<br/>
{% endfor %}
{% endblock %}

reservation/templates/reservation/date_search.html
{% block content %}
{% load static %}
<img src="{% static "/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/korean-air-img.png" %}">
<head>
<style>

</style>
</head>
<body>
<form action="/reservation/date_search_result/" method="get">
<div>
<br/>
<br/>
<br/>
<div>
{% csrf_token %}
<style>
ul{
    list-style:none;
}
</style>
<div id="daybox" style="position:absolute; margin-top:100px;">
<p style="font-size:12px;"><strong>출발일 기준 전체 항공권 조회하기</strong> | 아래에서 출발하시고 싶으신 날짜를 선택해 주세요</p>
<ul style="border:1px; color:gray;">
<li style="float:left"><strong>출발일 | {{form.daytogo}}</strong></li>
<li style="float:left; margin-left:30px;"><input type="submit", value="항공권 조회하기"></li>
</ul>
</div>
{% endblock %}
<br/>
<br/>
<br/>
<div>
<div>
<div id="address" style="position:absoltue; margin-top:300px">
<p style=font-size:12px>주) 대한항공 | 대표이사 : 우기홍 외 1명 | 주소 : 서울특별시 강서구 하늘길 260<br/>
대표전화 : 1588-2001 / 02-2656-2001<br/>
사업자 등록번호 : 110-81-14794 | 통신판매업신고 : 강서 제 16-3010<br/>
개인정보보호책임자 : 여객사업본부장 이진호 전무<br/>
© 1997-2020 KOREAN AIR<br/></p>
<br/>
</div>
</div>
</div>
</body>

reservation/templates/reservation/my_ticket_list.html
{% block content %}
{% for my_ticket in my_tickets %}
    번호 : {{ my_ticket.id }}<br/>
    예약자명  : {{ my_ticket.user }}<br/>
    출발지 : {{ my_ticket.starting_point }}<br/>
    도착지 : {{ my_ticket.arrival }}<br/>
    비행시간 : {{ my_ticket.flight_time }}<br/>
    가는날 : {{ my_ticket.daytogo }}<br/>
    오는날 : {{ my_ticket.comingDay }}<br/>
    가격 : {{ my_ticket.Price }}<br/>
    좌석등급 : {{ my_ticket.SeatClass }}
    <br/>
    <br/>
{% endfor %}
{% endblock %}
    

reservation/templates/reservation/payment.html
<head>
<style>
body {
    background: url("/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/myinfopic.jpeg")
}
</style>
</head>
<body>
<form action="{% url 'reservation:eticket_resend' %}" method="POST">
{% block content %}
{% csrf_token %}
<div id="wrapper" style="width:100%; text-align:center; font-size:13px; margin-top:150px;">
결제 및 예약정보 확인
</div>
<div id="wrapper" style="width:100%; text-align:center; font-size:13px; margin-top:70px;">
<strong>기종 |</strong> {{ courses.FlightNumber }}<br/>     
<strong>편명 |</strong> {{ courses.FlightAircraft }}<br/>     
<strong>출발지 |</strong> {{ courses.starting_point }}<br/>     
<strong>도착지 |</strong> {{ courses.arrival }}<br/>     
<strong>비행시간 |</strong> {{ courses.flight_time | date:'H 시간 i 분' }}<br/>     
<strong>가는날 |</strong> {{ courses.daytogo | date:'Y년 m월 d일' }}<br/>    
<strong>오는날 |</strong> {{ courses.comingDay | date:'Y년 m월 d일' }}<br/>
<strong>좌석등급 |</strong> {{ courses.SeatClass  }}<br/>
<strong>가격 |</strong> {{ courses.Price }}<br/>
<strong>예약자 |</strong> {{ request.user }}<br/>
</div>
<div id="wrapper" style="width:100%; text-align:center;">
<ul style="text-decoration:none; list-style:none; margin-left:-30px">
<li><input type="submit", name="payment", value="결제하기"></li>
<li><button name="course_choice" , value="{{ course.id }}">티켓재발송</li>
</ul>
</div>
{% endblock %}
</body>

reservation/templates/reservation/rev_start.html
{% block content %}
{% load static %}
<img src="{% static "/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/myinfopic.jpeg" %}">
<head>
<style>
</style>
</head>
<body>
<form action="/reservation/course_search/" method="GET">
<div>
</p>
<br/>
<br/>
<br/>
<div>
{% csrf_token %}
<style>
ul{
    list-style:none;
}
</style>

<div class="container">
<a href="{% url 'authentication:update' %}">회원정보수정</a>
</div>

<div id="wrapper" style="margin-bottom:30px; text-align:center;">

<div id="wrapper" style="margin-bottom:30px; margin-left:180px;">
<ul style="border:1px; color:gray;">
<li style="float:left"><strong>{{form.daytogo}}</strong></li>
<li style="float:left; margin-left:30px;"><strong>{{form.comingDay}}</strong></li>
<li style="float:left; margin-left:30px;">출발지 | {{ form.starting_point }}</li>
<li style="float:left; margin-left:30px;">도착지 | {{ form.arrival }}</li>
<li style="float:left; margin-left:30px;">좌석등급 | {{ form.SeatClass }}</li>
<li style="float:left; margin-top:60px; margin-left:-370px;"><input type="submit", value="항공권 조회하기"></li>
<li style="float:left; margin-top:60px; margin-left:-440px;"><input type="button", value="회원가입" onClick="location.href='/auth/register/'"></li>
<li style="float:left; margin-top:60px; margin-left:-500px;"><input type="button", value="로그인" onClick="location.href='/auth/login/'"></li>
<li style="float:left; margin-top:60px; margin-left:-590px;"><button type="button", name="uinfo", value="{{ myprofile_pks.id }}" onClick="location.href='/auth/myinfo/'">회원정보보기</button></li>
<li style="float:left; margin-top:60px; margin-left:-260px;"><button type="button", value="{{ my_ticket.id }}" name="myticket" onClick="location.href='/reservation/my_tc_list/'">나의에약내역보기</button></li>
<li style="float:left; margin-top:60px; margin-left:-660px;"><input type="button", value="회원탈퇴" onClick="location.href='/auth/unregister/'"></li>
<li style="float:left; margin-top:60px; margin-left:-730px;"><input type="button", value="로그아웃" onClick="location.href='/auth/logout/'"></li>
</ul>
</div>
{% endblock %}
</form>
<br/>
<br/>
<br/>
<div>
<div>
<div id="address" style="position:absoltue; margin-top:300px">
<p style=font-size:12px>주) 대한항공 | 대표이사 : 우기홍 외 1명 | 주소 : 서울특별시 강서구 하늘길 260<br/>
대표전화 : 1588-2001 / 02-2656-2001<br/>
사업자 등록번호 : 110-81-14794 | 통신판매업신고 : 강서 제 16-3010<br/>
개인정보보호책임자 : 여객사업본부장 이진호 전무<br/>
© 1997-2020 KOREAN AIR<br/></p>
<br/>
</div>
</div>
</div>
</body>

reservation/templates/reservation/sch_does_not_exist.html
{% block content %}
{% load static %}
<img src="{% static "/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/korean-air-img.png" %}">
<head>
<style>
</style>
</head>
<body>
<script>
alert("요청하신 날짜의 항공권이나 선택하신 좌석(일반석/프레스티지석/장애우석)이 존재하지 않습니다")
location.href= "/reservation/revstart/" 
</script>
<form action="/reservation/revstart/" method="get">
<div>
<p style=font-size:12px>항공권 예매 페이지 입니다.<br/>
구간별 검색이 가능합니다.<br/>
비수기에는 성수기보다 10% 가격 할인으로 제공되며 성수기에는 평소보다 10% 인상된 기격으로 제공됩니다.<br/>
</p>
<br/>
<br/>
<br/>
<div>
{% csrf_token %}
<style>
ul{
    list-style:none;
}
</style>
<div style="font-size:13px;">
<p>조회하신 여정의 항공권이 없습니다. 다른 여정을 선택해 주세요</p>
</div>
<div id="wrapper" style="margin-bottom:30px; font-size:13px;">
<li style="float:left; list-style:none;"><input type="submit", value="조회페이지로 돌아가기"></li>
</ul>

{% endblock %}
<br/>
<br/>
<br/>
<div>
<div>
<div id="address" style="position:absoltue; margin-top:300px">
<p style=font-size:12px>주) 대한항공 | 대표이사 : 우기홍 외 1명 | 주소 : 서울특별시 강서구 하늘길 260<br/>
대표전화 : 1588-2001 / 02-2656-2001<br/>
사업자 등록번호 : 110-81-14794 | 통신판매업신고 : 강서 제 16-3010<br/>
개인정보보호책임자 : 여객사업본부장 이진호 전무<br/>
© 1997-2020 KOREAN AIR<br/></p>
<br/>
</div>
</div>
</div>
</body>

reservation/templates/reservation/ticket_list.html
{% block content %}
{% for tc_list in tc_lists %}
    예약자명  : {{ tc_list.user }}<br/>
    출발지 : {{ tc_list.starting_point }}<br/>
    도착지 : {{ tc_list.arrival }}<br/>
    비행시간 : {{ tc_list.flight_time }}<br/>
    가는날 : {{ tc_list.daytogo }}<br/>
    오는날 : {{ tc_list.comingDay }}<br/>
    가격 : {{ tc_list.Price }}<br/>
    좌석등급 : {{ tc_list.SeatClass }}
    <br/>
    <br/>
{% endfor %}
{% endblock %}
    