BusinessRegister/urls.py
from django.urls import path
from .views import *

## app_name 안넣어 주면 NoReverseMatch 에러 발생
app_name = 'BusinessRegister'

urlpatterns = [
    path('join/', join, name='join'),
    path('join_success/', join_success, name='join_success'),
    path('drop/', drop, name='drop'),
    path('drop_success', drop_success, name='drop_success'),
]

STM/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join/', join, name='join'),
    path('join_success/', join_success, name='join_success'),
    path('drop/', drop, name='drop'),
    path('drop_success', drop_success, name='drop_success'),
]

reservation_project/urls.py
# -*- coding: utf-8 -*-
"""ReservationProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# app 고도화 작업 v1.0 DCR in AWS ECR

"""
dhdiagram.net/admin : 점포 관리자 서비스
dhdiagram.net/reservation : 예악서비스
dhdiagram.net/auth : 일반유저 회원가입 서비스
dhdiagram.net/data_save : 예액내역 저장 서비스
dhdiagram.net/ : api 서비스
dhdiagram.net/push : 문자발송 서비스
dhdiagram.net/stm : 최고 관리자(점포관리자) 회원가입
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')), 
    path('auth/', include('authentication.urls')), 
    path('data_save/', include('data_save.urls')), 
    path('', include('reservation_api.urls')), 
    path('push/', include('pushEngine.urls')), 
    path('businessRegister/', include('BusinessRegister.urls')),
    path('cafe_manager/', include('cafe_manager.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#administrator site page title
admin.site.site_header = '통합예약/적립시스템'

BusinessRegister/models.py
from django.db import models


class BusinessJoin(models.Model):
    business_id = models.CharField(max_length=10) #사업자 아이디
    MG_number = models.CharField(max_length=3)  #점포 번호 (관리자 번호)
    Store_name = models.CharField(max_length=100) #점포 명
    Store_phone = models.CharField(max_length=20)  #점포 전화번호
    Store_address_01 = models.CharField(max_length=100) # 점포주소 01
    Store_address_02 = models.CharField(max_length=100) #점포주소_02
    Representative = models.CharField(max_length=4) #대표자명
    store_number = models.CharField(max_length=5) #점포번호
    bln = models.CharField(max_length=20) #사업자 등록번호
    created_date = models.DateTimeField(auto_now_add=True) # 가입일 
    published_date = models.DateTimeField(null=True, blank=True) #데이터 생성일

BusinessRegister/forms.py
"""
회원가입 테이블
business_id, MG_number, Store_name ,Store_phone
Store_address_01, Store_address_02, Representative , store_number
bln  , stamp_design
"""

from django import forms
from .models import BusinessJoin
from django.shortcuts import render, redirect


class joinForm(forms.ModelForm):
    class Meta:
        model = BusinessJoin
        fields = ['business_id','MG_number','Store_name','Store_phone','Store_address_01','Store_address_02','Representative','store_number','bln']

    business_id = forms.CharField(label="사용할 점포 아이디", max_length=10, widget=forms.TextInput(attrs={'placeholder':'사용할 점포 아이디'}))
    MG_number = forms.CharField(label="사용할 점포 번호", max_length=3, widget=forms.TextInput(attrs={'placeholder':'사용할 점포 번호'}))
    Store_name = forms.CharField(label="점포 명", max_length=100, widget=forms.TextInput(attrs={'placeholder':'점포 명'}))
    Store_phone = forms.CharField(label="점포 연락처", max_length=20, widget=forms.TextInput(attrs={'placeholder':'점포 연락처'}))
    Store_address_01 = forms.CharField(label="점포주소", max_length=100, widget=forms.TextInput(attrs={'placeholder':'점포주소'}))
    Store_address_02 = forms.CharField(label="점포 상세주소", max_length=100, widget=forms.TextInput(attrs={'placeholder':'점포상세주소'}))
    Representative = forms.CharField(label="대표자명", max_length=4, widget=forms.TextInput(attrs={'placeholder':'대표자명'}))
    store_number = forms.CharField(label="점포번호", max_length=5, widget=forms.TextInput(attrs={'placeholder':"점포번호"}))
    bln = forms.CharField(label="사업자등록번호", max_length=20, widget=forms.TextInput(attrs={'placeholder':'사업자등록번호'}))
    

BusinessRegister/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.template.loader import render_to_string
from .forms import *
from django.utils import timezone
from twilio.rest import Client
import os

# 점포 관리자 회원 가입 후 SMS 문자 발송
def send_sms():
        account_sid = os.environ['TWILIO_ACCOUNT_SID']
        auth_token = os.environ['TWILIO_AUTH_TOKEN']
        client = Client(account_sid, auth_token)
        message = client.message.create(
            body = '점포관리자 회원가입이 완료되었습니다',
            from_ = '+16468460142',
            to = '+8201021764011'
        )


def join(request):
    if request.method == 'GET':
        form = joinForm(request.GET)
        return render(request, 'BusinessRegister/join.html', {'form':form})
    elif request.method == 'POST':
        form = joinForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            business_id = request.POST["business_id"]
            MG_number = request.POST["MG_number"]
            Store_name = request.POST["Store_name"]
            Store_phone = request.POST["Store_phone"]
            Store_address_01 = request.POST["Store_address_01"]
            Store_address_02 = request.POST["Store_address_02"]
            Representative = request.POST["Representative"]
            store_number = request.POST["store_number"]
            bln = request.POST["bln"]
            post.save()
            send_sms(message)
        return redirect('BusinessRegister:join_success')   


#점포 관리자 회원가입 성공
def join_success(request):
    business_members = BusinessJoin.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')[:1]
    return render(request, 'BusinessRegister/join_success.html', {'business_members':business_members})
    success_message = render_to_string('BusinessRegister/join_success.html', {'business_members':business_members})


#점포 관리자 회원탈퇴
def drop(request):
    return render(request, 'BusinessRegister/drop.html')


# 점포관리자 회원탈퇴 성공
def drop_success(request):
    return render(request, 'BusinessRegister/drop_success.html')

BusinessRegister/templates/BusinessRegister/drop_success.html
<div>
<strong>
점포회원탈퇴가 성공적으로 완료되었습니다<br/>
이용해 주셔서 감사합니다<br/>
</strong>
</div>

BusinessRegister/templates/BusinessRegister/index.html
#최고 관리자 회원가입 페이지

BusinessRegister/templates/BusinessRegister/join.html
{% block content %}
<form method="POST" action="{% url 'BusinessRegister:join' %}">{% csrf_token %}
<head>
<style>
body {    
background: url("/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/cloud.jpg")
}
li {
    list-style:none;
}
</style>
</head>
</head>
<div>
<p style=font-size:13px;>
<br/>
<br/>
<div style="width:100%; text-align:center; font-size:12px; margin-left:10px;">
<strong style="text-decoration:underline;">점포 정보 회원가입 페이지 입니다. 아래의 정보를 모두 빠짐없이 정확하게 입력하여 주세요</strong>
</div>
</p>
<div class="infobox" style="width:100%; text-align:center">
<ul>
<li>{{ form.business_id }}</li>
<li style="margin-top:10px;">{{ form.MG_number }}</li>
<li style="margin-top:10px;">{{ form.Store_name }}</li>
<li style="margin-top:10px;">{{ form.Store_phone }}</li>
<li style="margin-top:10px;">{{ form.Store_address_01 }}</li>
<li style="margin-top:10px;">{{ form.Store_address_02 }}</li>
<li style="margin-top:10px;">{{ form.Representative }}</li>
<li style="margin-top:10px;">{{ form.store_number }}</li>
<li style="margin-top:10px;">{{ form.bln }}</li>
</ul>
</div>
<div style="width:100%; text-align:center; margin-left:20px;">
<!--<input type="submit" value="가입하기">-->
<button type="submit" value="register_member">가입하기</button>
</form>
<!--<input type="button" value="예약페이지" onClick="location.href='/reservation/revstart/'">-->
</div>
{% endblock %}
<br/>
<br/>
<div>
<br/>
<br/>
</div>





{% comment %} {% block content %}

<form method="POST" action="{% url 'BusinessRegister:join' %}">{% csrf_token %}
<div class="box">
<ul>
<li>{{ form.business_id }}</li>
<li style="margin-top:10px;">{{ form.MG_number }}</li>
<li style="margin-top:10px;">{{ form.Store_name }}</li>
<li style="margin-top:10px;">{{ form.Store_phone }}</li>
<li style="margin-top:10px;">{{ form.Store_address_01 }}</li>
<li style="margin-top:10px;">{{ form.Store_address_02 }}</li>
<li style="margin-top:10px;">{{ form.Representative }}</li>
<li style="margin-top:10px;">{{ form.store_number }}</li>
<li style="margin-top:10px;">{{ form.bln }}</li>
<li style="margin-top:10px;">{{ form.stamp_design }}</li>
</ul>
</div>
<div style="width:100%, text-align:center; margin-left:20px'">
<button type="submit" value="add_register">가입하기</button>
</form>
</div>
{% endblock %} {% endcomment %}

BusinessRegister/templates/BusinessRegister/join_success.html
<div>
<strong>가입이 완료되었습니다.</strong>
<br/>
{% block content %}{% csrf_token %}
<ul>
{% for business_member in  business_members %}<br/>

사업자 아이디 : {{ business_member.business_id }}<br/>
점포번호 : {{ business_member.MG_number }}<br/>
점포명 : {{ business_member.Store_name }}<br/>
점포 연락처 :{{ business_member.Store_phone }}<br/>
점포 주소 : {{ business_member.Store_address_01 }}<br/>
점포 상세주소 : {{ business_member.Store_address_02 }}<br/>
대표자명 : {{ business_member.Representative }}<br/>
점포번호 : {{ business_member.store_number }}<br/>
사업자등록번호 : {{ business_member.bln }}<br/>
{% endfor %}
{% endblock %}
</ul>

</div>