STM/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join/', join, name='join'),
    path('join_success/', join_success, name='join_success'),
    path('drop/', drop, name='drop'),
    path('drop_success', drop_success, name='drop_success'),
]

authentication/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import login_view, logout, registration, registrationSuccess, already_exists, unregister,  myinfo, edit

app_name = "authentication"

urlpatterns = [
    path('login/', login_view, name='login'),
    path('account/', login_view, name='login'),
    path('logout/', logout, name='logout'),
    path('exit/', logout, name='logout'),
    path('register/', registration, name='registration'),
    path('registrationSuccess/', registrationSuccess, name='registrationSuccess'),
    path('already_exists/', already_exists, name='already_exists'),
    path('unregister/', unregister, name='unregister'),
    ##path('loginSuccess/', loginSuccess, name='loginSuccess'),
    path('myinfo/', myinfo, name='myinfo'),
    path('edit/', edit, name='edit'), #회원정보 수정
]

code_review/py/authentication/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import login_view, logout, registration, registrationSuccess, already_exists, unregister,  myinfo

app_name = "authentication"

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', registration, name='registration'),
    path('registrationSuccess/', registrationSuccess, name='registrationSuccess'),
    path('already_exists/', already_exists, name='already_exists'),
    path('unregister/', unregister, name='unregister'),
    ##path('loginSuccess/', loginSuccess, name='loginSuccess'),
    path('myinfo/', myinfo, name='myinfo'),
]

reservation_project/urls.py
# -*- coding: utf-8 -*-
"""ReservationProject URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# app 고도화 작업 v1.0 DCR in AWS ECR

"""
dhdiagram.net/admin : 점포 관리자 서비스
dhdiagram.net/reservation : 예악서비스
dhdiagram.net/auth : 일반유저 회원가입 서비스
dhdiagram.net/data_save : 예액내역 저장 서비스
dhdiagram.net/ : api 서비스
dhdiagram.net/push : 문자발송 서비스
dhdiagram.net/stm : 최고 관리자(점포관리자) 회원가입
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')), 
    path('auth/', include('authentication.urls')), 
    path('data_save/', include('data_save.urls')), 
    path('', include('reservation_api.urls')), 
    path('push/', include('pushEngine.urls')), 
    path('businessRegister/', include('BusinessRegister.urls')),
    path('cafe_manager/', include('cafe_manager.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#administrator site page title
admin.site.site_header = '통합예약/적립시스템'

authentication/forms.py
from django import forms
from .models import MyUser
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect


class registrationForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'koreanLastname', 'koreanFirstname', 'englishLastname', 'englishFirstname', 'email', 'password', 'address', 'detailAddress', 'phoneNumber']

    username = forms.CharField(label="로그인아이디", widget=forms.TextInput(attrs={'placeholder': '아이디', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    password = forms.CharField(label="패스워드", widget=forms.PasswordInput(attrs={'placeholder': '패스워드', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    koreanFirstname = forms.CharField(label="성", widget=forms.TextInput(attrs={'placeholder': '한국(성)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    koreanLastname = forms.CharField(label="이름", widget=forms.TextInput(attrs={'placeholder': '한국(이름)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    englishFirstname = forms.CharField(label="영문(성)", widget=forms.TextInput(attrs={'placeholder':'영문(성)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    englishLastname = forms.CharField(label="영문(이름)", widget=forms.TextInput(attrs={'placeholder': '영문(이름)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    address = forms.CharField(label="주소", widget=forms.TextInput(attrs={'placeholder': '주소', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    detailAddress = forms.CharField(label="상세주소", widget=forms.TextInput(attrs={'placeholder': '상세주소', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    phoneNumber = forms.CharField(label="휴대폰번호", widget=forms.TextInput(attrs={'placeholder': '휴대폰번호', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'})) 
    email = forms.CharField(label="이메일주소", widget=forms.TextInput(attrs={'placeholder': '이메일주소', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))


#회원정보 수정을 위한 폼
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class ModifyUserChangeForm(UserChangeForm):
    class Meta:
        model = MyUser
        fields = ['address','detailAddress','phoneNumber','email']



class MemberListForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'koreanLastname', 'koreanFirstname', 'englishLastname', 'englishFirstname', 'email', 'password', 'address', 'detailAddress', 'phoneNumber']

    username = forms.CharField(label="로그인아이디", widget=forms.TextInput(attrs={'placeholder': '아이디', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    password = forms.CharField(label="패스워드", widget=forms.PasswordInput(attrs={'placeholder': '패스워드', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    koreanFirstname = forms.CharField(label="성", widget=forms.TextInput(attrs={'placeholder': '한국(성)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    koreanLastname = forms.CharField(label="이름", widget=forms.TextInput(attrs={'placeholder': '한국(이름)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    englishFirstname = forms.CharField(label="영문(성)", widget=forms.TextInput(attrs={'placeholder':'영문(성)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    englishLastname = forms.CharField(label="영문(이름)", widget=forms.TextInput(attrs={'placeholder': '영문(이름)', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    address = forms.CharField(label="주소", widget=forms.TextInput(attrs={'placeholder': '주소', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    detailAddress = forms.CharField(label="상세주소", widget=forms.TextInput(attrs={'placeholder': '상세주소', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))
    phoneNumber = forms.CharField(label="휴대폰번호", widget=forms.TextInput(attrs={'placeholder': '휴대폰번호', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'})) 
    email = forms.CharField(label="이메일주소", widget=forms.TextInput(attrs={'placeholder': '이메일주소', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none; width:25em;'}))


class loginForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['username', 'password']
        # fields = "__all__"

    username = forms.CharField(label="아이디", help_text="가입시 입력하신 아이디를 입력하여 주세요", widget=forms.TextInput(attrs={'placeholder': '아이디', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none;'}))
    password = forms.CharField(label="패스워드", help_text="가입시 입력하신 패스워드를 입력하여 주세요", widget=forms.PasswordInput(attrs={'placeholder': '패스워드', 'style' : 'width:15em; height:3em; background-color:#F1F0EF; text-align:center; border:none;'}))
    

authentication/views.py
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from .forms import registrationForm, loginForm, MemberListForm
from .models import MyUser
from django.utils import timezone
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.http import JsonResponse
from django.contrib.auth.hashers import check_password
from django.contrib.auth import login, authenticate
from django.contrib import auth
from django.contrib.auth.hashers import make_password
import requests
import os
#sms message push service
from twilio.rest import Client
#ElasticCache
from django.views.decorators.cache import cache_page
#회원정보 수정을 위한 폼 불러오기
from django.contrib.auth.forms import UserChangeForm


def send_email(request):
    userlists = MyUser.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')[:1]
    print(userlists)
    title = "[통합예약시스템]회원가입을 환영합니다"
    html_messsage = render_to_string('authentication/registration_success.html', {'userlists': userlists})
    email = EmailMessage(title, html_messsage, to=[request.POST["email"]])
    email.content_subtype = "html"
    return email.send()
    account_sid = os.environ['TWILIO_ACCOUNT_SID']
    auth_token = os.environ['TWILIO_AUTH_TOKEN']
    client = Client(account_sid, auth_token)
    message = client.messages.create(
                            #body = html_messsage,
                            body='회원가입이 완료되었습니다(20201216)',
                            from_='+16468460142',
                            to='+8201021764011'
                            #to="+82" + request.POST["phoneNumber"]
                        )


#회원가입
def registration(request):
    if request.method == 'GET':
        form = registrationForm(request.GET)
        return render(request, 'authentication/registration.html' , {'form':form})
    elif request.method == 'POST':
        form = MemberListForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            koreanFirstname = request.POST["koreanFirstname"]
            koreanLastname = request.POST["koreanLastname"]
            englishLastname = request.POST["englishLastname"]
            englishFirstname = request.POST["englishFirstname"]
            address = request.POST["address"]
            email = request.POST["email"]
            detailAddress = request.POST["detailAddress"]
            phoneNumber = request.POST["phoneNumber"]
            password = request.POST["password"]
            #password = request.POST.get('password','-')
            post.set_password(password)
            post.save() ##폼 입력 후 DB에 저장
            send_email(request)
        return redirect('authentication:registrationSuccess')


def registrationSuccess(request):
    userlists = MyUser.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')[:1]
    return render(request, 'authentication/registration_success.html', {'userlists': userlists})


def already_exists(request):
    return render(request, 'authentication/already_exists.html')


def login_view(request):
    if request.method == 'GET':
        form = loginForm()
        return render(request, 'authentication/login.html', {'form': form})
    elif request.method == 'POST':
        username = request.POST.get('username','')
        password = request.POST.get('password','')

        user = authenticate(username=username, password=password)


    #로그인 시 만약 가입되어 있는 아이디가 없으면 팝업 메시지 출력
        if user is not None:
            login(request, user)
            return redirect('reservation:revstart')
        else:
            return render(request, 'authentication/idpw_does_not_exist.html')
            

# 로그아웃
def logout(request):
    auth.logout(request)
    form = loginForm()
    return render(request, 'authentication/login.html', {'form':form})


# 나의 정보 보기
#@cache_page(60 * 20) #ElaistcCache
def myinfo(request):
    myprofile_pks = MyUser.objects.get(id=request.POST['uinfo'])
    return render(request, 'authentication/myinfo.html', {'myprofile_pks': myprofile_pks})


# 회원탈퇴
def unregister(request):
        if request.method == 'GET':
            request.user.delete()
            form = loginForm()
        return render(request, 'authentication/unregister_success.html', {'form': form})
        

# 회원정보 수정 ### ModifyUserChangeForm
def edit(request):
    if request.method == 'POST':
        user_info_change = ModifyUserChangeForm(request.POST, instacne = request.username)
        if user_info_change.is_valid():
            user_info_change.save()
            return redirect('authentication:myinfo', request.user.username)
    else:
            user_info_change = ModifyUserChangeForm(instance = request.user)
            return render(request, 'authentication/update.html', {'user_info_change':user_info_change})

code_review/py/authentication/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .forms import registrationForm, loginForm
from .models import MyUser
from django.utils import timezone
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.http import JsonResponse
from django.contrib.auth.hashers import check_password
from django.contrib.auth import login, authenticate
from django.contrib import auth
from django.contrib.auth.hashers import make_password


# 회원가입 후 가입정보 이메일 발송
def usermail(request):
    userlists = MyUser.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')[:1]
    print(userlists)
    title = "[KOREANAIR]회원가입을 환영합니다"
    html_messsage = render_to_string('authentication/registration_success.html', {'userlists': userlists})
    email = EmailMessage(title, html_messsage, to=[request.POST["email"]])
    email.content_subtype = "html"
    return email.send()


# 회원가입
def registration(request):
    if request.method == 'GET':
        form = registrationForm(request.GET)
        return render(request, 'authentication/registration.html' , {'form':form})
    elif request.method == 'POST':
        form = registrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = request.POST.get('password', '-')
            user.set_password(password)
            user.save()
            usermail(request)
        return redirect('authentication:registrationSuccess')


def registrationSuccess(request):
    userlists = MyUser.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')[:1]
    return render(request, 'authentication/registration_success.html', {'userlists': userlists})


def already_exists(request):
    return render(request, 'authentication/already_exists.html')


def login_view(request):
    if request.method == 'GET':
        form = loginForm()
        return render(request, 'authentication/login.html', {'form': form})
    elif request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('reservation:revstart')
        else:
            return HttpResponse('아이디(ID) 또는 패스워드(PASSWORD)를 확인해 주세요')



# def loginSuccess(request):
#     user_pks = MyUser.objects.filter(username=request.POST['username'], password=request.POST['password'])
#     if user_pks:
#         return render(request, 'authentication/login_success.html', {'user_pks': user_pks})
#     else:
#         return render(request, 'authentication/login_failed.html')


def logout(request):
    if request.method == 'POST':
        return render(request, 'reservation/index.html')
    else:
        return render(request, 'reservation/logout_error.html')


#나의 정보 보기
def myinfo(request):
    myprofile_pks = MyUser.objects.get(id=request.POST['myinfo'])
    return render(request, 'authentication/myinfo.html', {'myprofile_pks': myprofile_pks})



def unregister(request):
        pass

code_review/py/authentication/templates/authentication/already_exists.html
<p>
<strong>
이미 해당 아이디로 가입되어 있는 정보가 있습니다.<br/>
다른 아이디를 이용해 주시거나 다시 확인해 주세요
</strong>
</p>

code_review/py/authentication/templates/authentication/login_failed.html
<script>
alert('아이디 또는 패스워드가 올바르지 않습니다, 로그인 페이지로 돌아갑니다')
location.href = "/auth/login/"
</script>

code_review/py/authentication/templates/authentication/login_success.html
<head>
<form action="{% url 'authentication:myinfo' %}" method="post">
<style>
ul {
    list-style:none;
},
body {
    background: url("/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/myinfopic.jpg")
}
</style>
</head>
<body>
<p style="font-size:13px; text-align:center; margin-top:120px;">
로그인에 성공하였습니다. 로그인 하신 아이디는 아래와 같습니다.<br/>

</p>
<br/>
<br/>
{% block content %}
{% for user_pk in user_pks %}
{% csrf_token %}
<div style="width:100%; text-align:center; font-size:12px; margin-left:-30px;">
<ul>
<li><strong>가입순서 | {{ user_pk.id }}</strong></li>
<li><strong>아이디 | {{ user_pk.username }}</strong></li>
<li><strong>이메일 |</strong> {{ user_pk.email }}</li>
<li><strong>주소 |</strong> {{ user_pk.address }}</li>
<li><strong>가입일 |</strong> {{ user_pk.created_date | date:'Y년 m월 d일 H시i분' }}</li>
<li><strong>상세주소 |</strong> {{ user_pk.detailAddress }}</li>
</ul>

<div style="margin-top:20px; margin-left:20px;">
<input type="button" value="회원탈퇴" onclick="location.href='/auth/unregister/'">
<input type="button" value="로그아웃" onclick="location.href='/auth/logout/'">
<input type="button" value="예약하기" onclick="location.href='/reservation/revstart/'">
<input type="button" value="예약내역" onclick="location.href='/reservation/myrevlist/'">
<button name="myinfo" value="{{ user_pk.id }}">회원정보</button>
</div>
</div>
{% endfor %}
{% endblock %}
</body>

code_review/py/authentication/templates/authentication/logout.html
logout

code_review/py/authentication/templates/authentication/logout_error.html
ERROR - LOGOUT

code_review/py/authentication/templates/authentication/myinfo.html
<style>
body {    
background: url("/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/myinfopic.jpeg")
}
</style>
<body>
<div style="font-size:13px; text-align:center; margin-top:200px;">
<strong>{{ myprofile_pks.koreanFirstname }} {{ myprofile_pks.koreanLastname }}</strong> 님의 회원정보는 아래와 같습니다.
</div>
<br/>
<br/>
{% block content %}
<div style="font-size:13px; text-align:center;">
<strong>아이디 |</strong> {{ myprofile_pks.username }}<br/>
<strong>이메일 |</strong> {{ myprofile_pks.email }}<br/>
<strong>주소 |</strong> {{ myprofile_pks.address }}<br/>
<strong>상세주소 |</strong> {{ myprofile_pks.detailAddress }}<br/>
<strong>가입일 |</strong>{{ myprofile_pks.created_date | date:'Y년 m월 d일 H시i분' }}<br/>
<strong>한국(성) |</strong>{{ myprofile_pks.koreanFirstname }}<br/>
<strong>한국(이름) |</strong>{{ myprofile_pks.koreanLastname }}<br/>
<strong>영문(성) |</strong>{{ myprofile_pks.englishLastname }}<br/>
<strong>영문(이름) |</strong>{{ myprofile_pks.englishFirstname }}<br/>
{% endblock %}
</body>

code_review/py/authentication/templates/authentication/registration.html
{% block content %}
<form method="POST" action="{% url 'authentication:registration' %}">{% csrf_token %}
<head>
<style>
body {    
background: url("/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/cloud.jpg")
}
li {
    list-style:none;
}
</style>
</head>
</head>
<div>
<p style=font-size:13px;>
<br/>
<br/>
<div style="width:100%; text-align:center; font-size:12px; margin-left:10px;">
<strong style="text-decoration:underline;">회원가입 페이지 입니다. 아래의 정보를 모두 빠짐없이 정확하게 입력하여 주세요</strong>
</div>
</p>
<div class="infobox" style="width:100%; text-align:center">
<ul>
<li>{{ form.username }}</li>
<li style="margin-top:10px;">{{ form.koreanLastname }}</li>  
<li style="margin-top:10px;">{{ form.koreanFirstname }}</li>
<li style="margin-top:10px;">{{ form.englishLastname }}</li>
<li style="margin-top:10px;">{{ form.englishFirstname }}</li>
<li style="margin-top:10px;">{{ form.email }}</li>
<li style="margin-top:10px;">{{ form.password }}</li>
<li style="margin-top:10px;">{{ form.address }}</li>
<li style="margin-top:10px;">{{ form.detailAddress }}</li>
<li style="margin-top:10px;">{{ form.phoneNumber }}</li>
</ul>
</div>
<div style="width:100%; text-align:center; margin-left:20px;">
<input type="submit" value="가입하기">
</form>
<input type="button" value="예약페이지" onClick="location.href='/reservation/revstart/'">
</div>
{% endblock %}
<br/>
<br/>
<div>
<br/>
<br/>
</div>

code_review/py/authentication/templates/authentication/registration_success.html
<head>
<style>
body {
    background: url("/Users/dohyoungkim/Downloads/Reservation-search-app/Reservation-app/ReservationProject/static/myinfopic.jpg")
}
li {
    list-style:none;
}
ul {
    list-style:none;
}
</style>
</head>
<div style="width:100%; font-size:12px; text-decoration:underline; text-align:center; margin-top:200px;">
입력하신 가입정보는 다음과 같습니다. 정보가 올바른지 확인해 주시기 바랍니다.<br/>
가입완료 후 로그인시 입력하신 아이디/패스워드를 정확히 입력해 주시기 바랍니다.<br/>
</div>
</p>
<div style="width:100%; font-size:13px; text-align:center; margin-top:70px;">
<ul>
{% block content %}{% csrf_token %}
{% for userlist in userlists %}
<li>{{ userlist.username }}</li>
<li>{{ userlist.email }}</li>
<li>{{ userlist.koreanLastname }}</li>     
<li>{{ userlist.koreanFirstname }}</li>
<li>{{ userlist.address }}</li>
<li>{{ userlist.detailAddress }}</li>
<li>{{ userlist.created_date | date:'Y년 m월 d일 H시i분' }}</li>
</ul>
{% endfor %}
<div style="font-size:12px; text-decoration:underline; margin-left:30px;"> 
<strong>가입해 주셔서 대단히 감사합니다.</strong>
</div>
<div style="margin-top:20px; margin-left:40px;">
<input type="button" value="로그인 바로가기" onclick="location.href='/auth/login/'"></a>
</div>
{% endblock %}